// <auto-generated />
using System;
using BigDeckPlays.DAL.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace BigDeckPlays.DAL.Migrations
{
    [DbContext(typeof(BigDeckPlaysContext))]
    partial class BigDeckPlaysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("BigDeckPlays.DAL.db.Card", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Cmc")
                        .HasColumnName("cmc")
                        .HasColumnType("integer");

                    b.Property<string>("Colors")
                        .HasColumnName("colors")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Cost")
                        .HasColumnName("cost")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("OracleText")
                        .HasColumnName("oracle_text")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Power")
                        .HasColumnName("power")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("SubTypes")
                        .HasColumnName("sub_types")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Toughness")
                        .HasColumnName("toughness")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Types")
                        .HasColumnName("types")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("card_name_key");

                    b.ToTable("card","dbo");
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.CardSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnName("card_id")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<decimal?>("HighPrice")
                        .HasColumnName("high_price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LowPrice")
                        .HasColumnName("low_price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MedianPrice")
                        .HasColumnName("median_price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnName("quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SetId")
                        .IsRequired()
                        .HasColumnName("set_id")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("SetId");

                    b.ToTable("card_set","dbo");
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.CardTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnName("card_id")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int>("TagId")
                        .HasColumnName("tag_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("TagId");

                    b.ToTable("card_tag","dbo");
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Commander")
                        .IsRequired()
                        .HasColumnName("commander")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Commander");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("deck_name_key");

                    b.ToTable("deck","dbo");
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.DeckCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnName("card_id")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int>("DeckId")
                        .HasColumnName("deck_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("quantity")
                        .HasColumnType("integer")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("deck_card","dbo");
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.DeckTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DeckId")
                        .HasColumnName("deck_id")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("quantity")
                        .HasColumnType("integer")
                        .HasDefaultValueSql("1");

                    b.Property<int>("TagId")
                        .HasColumnName("tag_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("TagId");

                    b.ToTable("deck_tag","dbo");
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.Set", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Border")
                        .HasColumnName("border")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int?>("Number")
                        .HasColumnName("number")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnName("type")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Url")
                        .HasColumnName("url")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("set_name_key");

                    b.ToTable("set","dbo");
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("tag","dbo");
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.CardSet", b =>
                {
                    b.HasOne("BigDeckPlays.DAL.db.Card", "Card")
                        .WithMany("CardSet")
                        .HasForeignKey("CardId")
                        .HasConstraintName("card_set_card_id_fkey")
                        .IsRequired();

                    b.HasOne("BigDeckPlays.DAL.db.Set", "Set")
                        .WithMany("CardSet")
                        .HasForeignKey("SetId")
                        .HasConstraintName("card_set_set_id_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.CardTag", b =>
                {
                    b.HasOne("BigDeckPlays.DAL.db.Card", "Card")
                        .WithMany("CardTag")
                        .HasForeignKey("CardId")
                        .HasConstraintName("card_tag_card_id_fkey")
                        .IsRequired();

                    b.HasOne("BigDeckPlays.DAL.db.Tag", "Tag")
                        .WithMany("CardTag")
                        .HasForeignKey("TagId")
                        .HasConstraintName("card_tag_tag_id_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.Deck", b =>
                {
                    b.HasOne("BigDeckPlays.DAL.db.Card", "CommanderNavigation")
                        .WithMany("Deck")
                        .HasForeignKey("Commander")
                        .HasConstraintName("deck_commander_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.DeckCard", b =>
                {
                    b.HasOne("BigDeckPlays.DAL.db.Card", "Card")
                        .WithMany("DeckCard")
                        .HasForeignKey("CardId")
                        .HasConstraintName("deck_card_card_id_fkey")
                        .IsRequired();

                    b.HasOne("BigDeckPlays.DAL.db.Deck", "Deck")
                        .WithMany("DeckCard")
                        .HasForeignKey("DeckId")
                        .HasConstraintName("deck_card_deck_id_fkey")
                        .IsRequired();
                });

            modelBuilder.Entity("BigDeckPlays.DAL.db.DeckTag", b =>
                {
                    b.HasOne("BigDeckPlays.DAL.db.Deck", "Deck")
                        .WithMany("DeckTag")
                        .HasForeignKey("DeckId")
                        .HasConstraintName("deck_tag_deck_id_fkey")
                        .IsRequired();

                    b.HasOne("BigDeckPlays.DAL.db.Tag", "Tag")
                        .WithMany("DeckTag")
                        .HasForeignKey("TagId")
                        .HasConstraintName("deck_tag_tag_id_fkey")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
